"""add structured policy rule conditions

Revision ID: a9959544b667
Revises: 1573db608f48
Create Date: 2026-08-25 11:30:26.589283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9959544b667'
down_revision: Union[str, Sequence[str], None] = '1573db608f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_rules', sa.Column('condition', sa.JSON(), nullable=False))
    op.add_column('policy_rules', sa.Column('action', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_rules', 'action')
    op.drop_column('policy_rules', 'condition')
    # ### end Alembic commands ###
