"""associate purchase requests with policies

Revision ID: e4a44e131ef2
Revises: dcc5f8e468df
Create Date: 2026-08-25 12:24:00.810535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a44e131ef2'
down_revision: Union[str, Sequence[str], None] = 'dcc5f8e468df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requests', sa.Column('policy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_requests', 'policies', ['policy_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_requests', type_='foreignkey')
    op.drop_column('purchase_requests', 'policy_id')
    # ### end Alembic commands ###
