"""add rfq management tables

Revision ID: e4dee5678eaa
Revises: f0c6748fb066
Create Date: 2026-08-29 02:47:13.796234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dee5678eaa'
down_revision: Union[str, Sequence[str], None] = 'f0c6748fb066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_id'), 'rfqs', ['id'], unique=False)
    op.create_index(op.f('ix_rfqs_purchase_request_id'), 'rfqs', ['purchase_request_id'], unique=False)
    op.create_index(op.f('ix_rfqs_rfq_number'), 'rfqs', ['rfq_number'], unique=True)
    op.create_index(op.f('ix_rfqs_status'), 'rfqs', ['status'], unique=False)
    op.create_table('rfq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['purchase_request_item_id'], ['purchase_request_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_items_id'), 'rfq_items', ['id'], unique=False)
    op.create_index(op.f('ix_rfq_items_rfq_id'), 'rfq_items', ['rfq_id'], unique=False)
    op.create_table('rfq_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id', 'vendor_id', name='uq_rfq_vendor')
    )
    op.create_index(op.f('ix_rfq_vendors_id'), 'rfq_vendors', ['id'], unique=False)
    op.create_index(op.f('ix_rfq_vendors_rfq_id'), 'rfq_vendors', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_rfq_vendors_vendor_id'), 'rfq_vendors', ['vendor_id'], unique=False)
    op.alter_column('vendors', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vendors', 'tax_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'tax_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vendors', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_rfq_vendors_vendor_id'), table_name='rfq_vendors')
    op.drop_index(op.f('ix_rfq_vendors_rfq_id'), table_name='rfq_vendors')
    op.drop_index(op.f('ix_rfq_vendors_id'), table_name='rfq_vendors')
    op.drop_table('rfq_vendors')
    op.drop_index(op.f('ix_rfq_items_rfq_id'), table_name='rfq_items')
    op.drop_index(op.f('ix_rfq_items_id'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_index(op.f('ix_rfqs_status'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_rfq_number'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_purchase_request_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_id'), table_name='rfqs')
    op.drop_table('rfqs')
    # ### end Alembic commands ###
