"""create vendors table

Revision ID: f0c6748fb066
Revises: 06ff90055fba
Create Date: 2026-08-29 01:10:46.099771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c6748fb066'
down_revision: Union[str, Sequence[str], None] = '06ff90055fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('vendors', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('vendors', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('vendors', sa.Column('tax_id', sa.String(length=100), nullable=True))
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_index(op.f('ix_vendors_tax_id'), 'vendors', ['tax_id'], unique=True)
    op.drop_column('vendors', 'display_name')
    op.drop_column('vendors', 'tax_identifier')
    op.drop_column('vendors', 'legal_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('tax_identifier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vendors_tax_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.alter_column('vendors', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('vendors', 'tax_id')
    op.drop_column('vendors', 'postal_code')
    op.drop_column('vendors', 'state')
    op.drop_column('vendors', 'city')
    op.drop_column('vendors', 'address')
    op.drop_column('vendors', 'name')
    # ### end Alembic commands ###
