"""add approval decision comments

Revision ID: f56704715da9
Revises: e4a44e131ef2
Create Date: 2026-08-26 20:20:12.183464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56704715da9'
down_revision: Union[str, Sequence[str], None] = 'e4a44e131ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_steps', sa.Column('decided_by', sa.Integer(), nullable=True))
    op.add_column('approval_steps', sa.Column('decision_comments', sa.String(length=2000), nullable=True))
    op.drop_constraint(op.f('approval_steps_approved_by_fkey'), 'approval_steps', type_='foreignkey')
    op.create_foreign_key(None, 'approval_steps', 'users', ['decided_by'], ['id'])
    op.drop_column('approval_steps', 'approved_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_steps', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'approval_steps', type_='foreignkey')
    op.create_foreign_key(op.f('approval_steps_approved_by_fkey'), 'approval_steps', 'users', ['approved_by'], ['id'])
    op.drop_column('approval_steps', 'decision_comments')
    op.drop_column('approval_steps', 'decided_by')
    # ### end Alembic commands ###
